name: new_renitek
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  provider: ^6.0.5
  percent_indicator: ^4.2.2
  nsd: ^4.0.3
  connectivity_plus: ^6.1.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.1
  shared_preferences: ^2.1.2
  http: ^1.6.0
  flutter_reactive_ble: ^5.4.0
  intl: ^0.20.2
  app_settings: ^9.0.0
  url_launcher: ^6.3.2
  file_picker: ^11.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/app_icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.ttf
          weight: 400
        - asset: assets/fonts/helvetica-neue-medium.ttf
          weight: 600
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
